name: interactions

repository: https://github.com/hongmono/flutter_interactions

packages:
  - apps/**
  - packages/**
  - packages/*/example

scripts:
  analyze:
    exec: dart analyze .

command:
  version:
    message: |
      {new_package_versions}

    hooks:
      post: |
        git push > /dev/null 2>&1