name: interactions

packages:
  - apps/**
  - packages/**
  - packages/*/example

scripts:
  analyze:
    exec: dart analyze .

command:
  version:
    message: |
      {new_version}

    hooks:
      post: echo "{MELOS_PACKAGE_VERSION} Post version command"